###
POST  http://localhost:9000/api/users HTTP/1.1
Content-Type: application/json

{
    "name": "George Mendel",
    "age": "81",
    "email": "georgemendely@email.com"
}

###
GET http://localhost:9000/api/users HTTP/1.1

###
GET http://localhost:9000/api/users/<id> HTTP/1.1

###
PUT http://localhost:9000/api/users/<id> HTTP/1.1
Content-Type: application/json

{
    "name": "George Mendel",
    "age": "81",
    "email": "georgemendely@email.com"
}

###
DELETE http://localhost:9000/api/users/<id>HTTP/1.1
